#!/bin/sh
case "$1" in
    start) /usr/sbin/wifisetup.sh start ;;
    stop) /usr/sbin/wifisetup.sh stop ;;
    restart) /usr/sbin/wifisetup.sh restart ;;
    *) echo "Usage: $0 {start|stop|restart}" ;;
esac
